services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: portfolio-backend1
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/portfolio
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Veeru@2005
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8083:8080"
    networks:
      - portfolio-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: portfolio-frontend1
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - backend
    networks:
      - portfolio-net

networks:
  portfolio-net:
    driver: bridge
