
services:
  db:
    image: mysql:8.0
    container_name: portfolio-db
    restart: always
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_ROOT_PASSWORD: Veeru@2005
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - portfolio-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pVeeru@2005"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile.backend
    container_name: portfolio-backend1
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/portfolio
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Veeru@2005
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy # wait for MySQL to pass healthcheck
    ports:
      - "8083:8080"
    networks:
      - portfolio-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: portfolio-frontend1
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - backend
    networks:
      - portfolio-net

volumes:
  db_data:

networks:
  portfolio-net:
    driver: bridge
