services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: portfolio-backend1
    ports:
      - "8083:8080"
    networks:
      - portfolio-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: portfolio-frontend1
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - backend
    networks:
      - portfolio-net

networks:
  portfolio-net:
    driver: bridge
